### ISSUE TITLE
Migration checklist

### ISSUE THREAD

**Issue by anthonyronda** [unitedfantasytoolkit/uft#1]
- [x] clone vttred/ose into uft/uft
- [x] set uft/uft as upstream (may later use git submodule or npm module)
- [x] set vttred/ose-content as archived
- [x] clone vttred/ose-content into uft/classic-compendium (or similar)

more checklist items to follow

**Comment by anthonyronda** [comment]
- [x] create an npm org
- [ ] set up some npm packages
- [ ] set up a new i18n provider
- [x] new UFT logo
- [ ] new README badges
- [ ] submitted to Foundry VTT
- [ ] README: new installation instructions
- [ ] README: new compendium list (possibly a link to a list in docs?)
- [ ] README: new support section
- [ ] README: new licensing inquiries section
- [ ]
